### ISSUE TITLE
how to install this in jeston tx1 ubuntu 16.04

### ISSUE THREAD

**Issue by fgq1992** [matham/pyflycap2#1]
Sorry to bother you. I want to use pyflycap2 in jeston tx1 based on ARM. Dose your code support this system?

**Comment by matham** [comment]
Please take a look at https://matham.github.io/pyflycap2/installation.html. The python code is not OS specific so it's just a matter of getting it to find the binaries and headers. I have tested that instructions on ubuntu and it worked for me.

**Comment by fgq1992** [comment]
Your code also worked well on my ubuntu 16.04 system when I installed the flycapture driver xxx_amd64 in my laptop. But in the Jetson tx1, I need to install the driver xxx_arm64.， which means some required files may be changed.  How can I modify your code to satisfy its use on ARM-ubuntu OS?

**Comment by matham** [comment]
I don't have that machine so I cannot test, but if you installed their drivers with `install_flycapture.sh` then all you should need to do is `export PYFLYCAP2_INCLUDE=/usr/include/flycapture`. 

The libraries we link with is listed here: https://github.com/matham/pyflycap2/blob/master/setup.py#L35. If they are different for your platform then you may need to change it there.

Are you getting a error?

**Comment by fgq1992** [comment]
Thank you very much for your reply. I did't installed the drivers with install_flycapture.sh. I need use another driver which can work on arm_machine. The installation process is here: http://www.ptgrey.com/KB/10357.  But they are very similar. The difference between them is that arm drivers  didn't have libs like libflycapture-c.so and libflycapturegui-c.so, which are required in your code. But rest of the libs are almost identical. 
So based on the libs that arm_machine have, I want to do some changes in your code,  where should I make the changes?

**Comment by matham** [comment]
Looking at that link and at the arm tar.gz file, after you extract it is says to do `sudo cp libflycapture* /usr/lib`. This copies the `so` binaries into `/usr/lib`. We need the binaries under `libflycapture*/c` which hopefully should have been copied as well to `/usr/lib/c`.

So then before compiling pyflycap2 you need to do `export PYFLYCAP2_LIB=/usr/lib/c`. Similarly, we need the headers. You can provide them by doing e.g. `export PYFLYCAP2_INCLUDE=path/to/flycapture-<version>_arm/include`. The binaries will be needed even after compiling so you need to add them to the LD path if it isn't found automatically.

**Comment by fgq1992** [comment]
With your help, I have found the relevant  `so` binaries. But the `FlyCapture2GUI_C ` is still missing. When looking at  `include/C/ `or` lib/C ` in arm tar.gz file, the file could not be found. And the error information was: `pyflycap2/interface.c:474:32: fatal error: C/FlyCapture2GUI_C.h: No such file or directory
compilation terminated.
`

**Comment by matham** [comment]
Huh, looks like the arm package doesn't come with the gui headers. It does seem to come with the binaries which suggests that it's an oversight by pt gray where they forgot to include it. I would contact pt gray and ask why `C/FlyCapture2GUI_C.h` is missing from the arm package. Lemme know what they say.
