### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by migsdigs** [matham/pyflycap2#3]
I tried installing PyFlyCap2 with pip install. As shown below:
```python
pip install pyflycapture2
```

This produces the following error:

C:\Users\migue>pip install pyflycapture2
Collecting pyflycapture2
  Using cached pyflycapture2-0.1.tar.gz (68 kB)
Requirement already satisfied: numpy in c:\users\migue\appdata\local\programs\python\python38-32\lib\site-packages (from pyflycapture2) (1.18.2)
Building wheels for collected packages: pyflycapture2
  Building wheel for pyflycapture2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\migue\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\migue\\AppData\\Local\\Temp\\pip-install-d9vlnjzy\\pyflycapture2\\setup.py'"'"'; __file__='"'"'C:\\Users\\migue\\AppData\\Local\\Temp\\pip-install-d9vlnjzy\\pyflycapture2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\migue\AppData\Local\Temp\pip-wheel-rjd2qqda'
       cwd: C:\Users\migue\AppData\Local\Temp\pip-install-d9vlnjzy\pyflycapture2\
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_ext
  skipping 'src\flycapture2.c' Cython extension (up-to-date)
  building 'flycapture2' extension
  creating build
  creating build\temp.win32-3.8
  creating build\temp.win32-3.8\Release
  creating build\temp.win32-3.8\Release\src
  D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/flycapture/C "-IC:/Program Files (x86)/Point Grey Research/FlyCapture2/include/C" -Ic:\users\migue\appdata\local\programs\python\python38-32\lib\site-packages\numpy\core\include -Ic:\users\migue\appdata\local\programs\python\python38-32\include -Ic:\users\migue\appdata\local\programs\python\python38-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\flycapture2.c /Fobuild\temp.win32-3.8\Release\src\flycapture2.obj
  flycapture2.c
  src\flycapture2.c(235): fatal error C1083: Cannot open include file: 'FlyCapture2Defs_C.h': No such file or directory
  error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pyflycapture2
  Running setup.py clean for pyflycapture2
Failed to build pyflycapture2
Installing collected packages: pyflycapture2
    Running setup.py install for pyflycapture2 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\migue\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\migue\\AppData\\Local\\Temp\\pip-install-d9vlnjzy\\pyflycapture2\\setup.py'"'"'; __file__='"'"'C:\\Users\\migue\\AppData\\Local\\Temp\\pip-install-d9vlnjzy\\pyflycapture2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\migue\AppData\Local\Temp\pip-record-fjwu0ae7\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\migue\appdata\local\programs\python\python38-32\Include\pyflycapture2'
         cwd: C:\Users\migue\AppData\Local\Temp\pip-install-d9vlnjzy\pyflycapture2\
    Complete output (13 lines):
    running install
    running build
    running build_ext
    skipping 'src\flycapture2.c' Cython extension (up-to-date)
    building 'flycapture2' extension
    creating build
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    creating build\temp.win32-3.8\Release\src
    D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/flycapture/C "-IC:/Program Files (x86)/Point Grey Research/FlyCapture2/include/C" -Ic:\users\migue\appdata\local\programs\python\python38-32\lib\site-packages\numpy\core\include -Ic:\users\migue\appdata\local\programs\python\python38-32\include -Ic:\users\migue\appdata\local\programs\python\python38-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\flycapture2.c /Fobuild\temp.win32-3.8\Release\src\flycapture2.obj
    flycapture2.c
    src\flycapture2.c(235): fatal error C1083: Cannot open include file: 'FlyCapture2Defs_C.h': No such file or directory
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\migue\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\migue\\AppData\\Local\\Temp\\pip-install-d9vlnjzy\\pyflycapture2\\setup.py'"'"'; __file__='"'"'C:\\Users\\migue\\AppData\\Local\\Temp\\pip-install-d9vlnjzy\\pyflycapture2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\migue\AppData\Local\Temp\pip-record-fjwu0ae7\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\migue\appdata\local\programs\python\python38-32\Include\pyflycapture2' Check the logs for full command output.

This is the same error I incurred when following the instructions from PyFlyCap2 at [PyFlyCap2 installation](http://matham.github.io/pyflycap2/installation.html)

Any assistance would be appreciated. Thank you.

**Comment by matham** [comment]
This is because you're installing on Python 3.8 and I didn't create a pre-compiled wheel for 3.8. We depend on [pythonnet](https://pypi.org/project/pythonnet/) and they haven't released 3.8 yet.

Try installing it on Python 3.7.

**Comment by matham** [comment]
Looking more closely, you did `pip install pyflycapture2`, but it should be `pip install pyflycap2`.
